version: '3.7'

services:

  db:
    container_name: "database"
    #restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    build:
      context: .
      dockerfile: db.Dockerfile
    #volumes:
      #- ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  api:
    container_name: "api"
    build:
      context: .
      dockerfile: api.Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - db
    volumes:
      - .:/app/

volumes:
  database_postgres:
